steps:
  - label: nix-installer-aarch64-darwin
    agents:
      mac: 1
      system: aarch64-darwin
      nix: 1
    command:
      - nix --extra-experimental-features "nix-command flakes" build .#packages.aarch64-darwin.nix-installer -L
      - cp result/bin/nix-installer ./nix-installer-aarch64-darwin
      - buildkite-agent artifact upload nix-installer-aarch64-darwin
  - label: nix-installer-x86_64-linux
    agents:
      system: x86_64-linux
      nix: 1
    command:
      - nix --extra-experimental-features "nix-command flakes" build .#packages.x86_64-linux.nix-installer-static -L
      - cp result/bin/nix-installer ./nix-installer-x86_64-linux
      - buildkite-agent artifact upload nix-installer-x86_64-linux
  - label: nix-installer-aarch64-linux
    agents:
      system: aarch64-linux
      nix: 1
    command:
      - nix --extra-experimental-features "nix-command flakes" build .#packages.aarch64-linux.nix-installer-static -L
      - cp result/bin/nix-installer ./nix-installer-aarch64-linux
      - buildkite-agent artifact upload nix-installer-aarch64-linux
