steps:
  - label: nix-installer-aarch64-darwin
    agents:
      mac: 1
      system: aarch64-darwin
      nix: 1
    command:
      - nix --extra-experimental-features "nix-command flakes" build .#packages.aarch64-darwin.nix-installer -L
      - cp result/bin/nix-installer ./nix-installer-aarch64-darwin
      - buildkite-agent artifact upload nix-installer-aarch64-darwin
