name: Build x86_64 Linux (static)
concurrency: x86_64-linux-${{ github.sha }}
on: 
  workflow_call:

jobs:
  build-x86_64-linux:
    name: Build x86_64 Linux (static)
    runs-on: UbuntuLatest32Cores128G
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build the installer
        run: |
          nix build .#packages.x86_64-linux.nix-installer-static -L
          cp result/bin/nix-installer .
      - name: Create GitHub cache from build artifacts
        uses: actions/cache/save@v3
        with:
          path: nix-installer
          key: x86_64-linux-artifacts-${{ github.sha }}
