name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  id-token: "write"
  contents: "read"

jobs:
  build-x86_64-linux:
    uses: ./.github/workflows/build-x86_64-linux.yml

  run-x86_64-linux-release-checks:
    name: Run x86_64 Linux release checks
    runs-on: UbuntuLatest64Cores256GX86
    needs: [build-x86_64-linux]
    if: contains(github.ref, 'release-') || contains(github.head_ref, 'release-')
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Restore Github cache artifacts
        uses: actions/cache/restore@v3
        with:
          path: nix-installer
          key: x86_64-linux-artifacts-${{ github.sha }}
      - name: Move & set executable
        run: |
          mkdir install-root
          cp nix-installer.sh install-root/nix-installer.sh
          mv ./nix-installer install-root/nix-installer-x86_64-linux
          chmod +x install-root/nix-installer-x86_64-linux install-root/nix-installer.sh

      - run: echo $ACTIONS_ID_TOKEN_REQUEST_URL | sha256sum -
      - run: echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | sha256sum -

      - name: Initial install
        uses: DeterminateSystems/nix-installer-action@main
        with:
          backtrace: full
          determinate: true
          local-root: install-root/
          log-directives: nix_installer=debug
          logger: pretty
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-gha-cache: false
          source-pr: 114

      - run: nix flake check -L
      - run: |
          nix build \
            -L --tarball-ttl 0 --keep-going \
            .#hydraJobs.container-test.all.x86_64-linux.all \
            .#hydraJobs.vm-test.all.x86_64-linux.all

      - run: echo $ACTIONS_ID_TOKEN_REQUEST_URL | sha256sum -
      - run: echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | sha256sum -
