name: Release PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    # TODO: do we want to only trigger this on PRs that target main?
    # that would make PRs that target e.g. other PRs (or non-main branches) not get artifacts uploaded
    # branches:
    #   - 'main'

jobs:
  release:
    # Only intra-repo PRs are allowed to have PR artifacts uploaded
    if: ${{ github.event.pull_request.head.repo.full_name == 'DeterminateSystems/nix-installer' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Buildkite Artifacts
        uses: EnricoMi/download-buildkite-artifact-action@v1.14
        with:
          buildkite_token: ${{ secrets.BUILDKITE_TOKEN }}
          output_path: artifacts
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_S3_UPLOAD_ROLE }}
          aws-region: us-east-2
      - name: Publish Release (PR)
        env:
          AWS_BUCKET: ${{ secrets.AWS_S3_UPLOAD_BUCKET }}
        run: |
          # If the revision directory has already been created in S3 somehow, we don't want to reupload
          aws s3 ls "$AWS_BUCKET"/"$GITHUB_SHA"/ && exit 1

          sudo chown $USER: -R artifacts/

          PR="pr_${{ github.event.pull_request.number }}"
          mkdir "$PR"
          mkdir "$GITHUB_SHA"

          sed -i "s@https://install.determinate.systems/nix@https://install.determinate.systems/nix/rev/$GITHUB_SHA@" nix-installer.sh
          cp nix-installer.sh "$GITHUB_SHA"/
          cp nix-installer.sh "$PR"/

          for artifact in $(find artifacts/ -type f); do
            chmod +x "$artifact"
            cp "$artifact" "$GITHUB_SHA"/
            cp "$artifact" "$PR"/
          done

          aws s3 sync "$GITHUB_SHA"/ s3://"$AWS_BUCKET"/"$GITHUB_SHA"/ --acl public-read
          aws s3 sync "$PR"/ s3://"$AWS_BUCKET"/"$PR"/ --acl public-read
